# -*- coding: utf-8 -*-
# """fitness project.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1U5GQp6Fbv61VX35SLiUmg5fiLJ39MJYI
# """

# !pip install streamlit
# !pip install genai
# !pip install reportlab
# !pip install platypus



import streamlit as st
import pandas as pd
from google import genai
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
import tempfile

import os

api_key = os.getenv("GEMINI_API_KEY")
from google import genai

client = genai.Client(
    api_key=api_key
)
def calculate_bmi(weight, height):
    height_m = height / 100
    return round(weight / (height_m ** 2), 2)

def calculate_water(weight):
    return round(weight * 0.033, 2)

def calculate_calories(age, gender, weight, height, activity):
    if gender == "Male":
        bmr = 10 * weight + 6.25 * height - 5 * age + 5
    else:
        bmr = 10 * weight + 6.25 * height - 5 * age - 161

    return round(bmr * activity)

def ask_gemini(prompt):
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    return response.text

def create_pdf(content):
    temp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    doc = SimpleDocTemplate(temp.name)

    styles = getSampleStyleSheet()

    story = [
        Paragraph(content, styles["BodyText"])
    ]

    doc.build(story)

    return temp.name

# streamlit
st.set_page_config(
    page_title="AI Fitness Coach",
    layout="wide"
)

st.title("🏋️ AI Fitness Coach")

# ---------- SIDEBAR ----------

st.sidebar.header("User Profile")

age = st.sidebar.number_input(
    "Age",
    16,
    80,
    22
)

gender = st.sidebar.selectbox(
    "Gender",
    ["Male", "Female"]
)

weight = st.sidebar.number_input(
    "Weight (kg)",
    30.0,
    200.0,
    70.0
)

height = st.sidebar.number_input(
    "Height (cm)",
    120.0,
    220.0,
    170.0
)

goal = st.sidebar.selectbox(
    "Goal",
    [
        "Fat Loss",
        "Maintenance",
        "Muscle Gain"
    ]
)

activity = st.sidebar.selectbox(
    "Activity Level",
    ["Sedentary", "Light", "Moderate", "Heavy"]
)
activity_level = {
    "Sedentary": 1.2,
    "Light": 1.375,
    "Moderate": 1.55,
    "Heavy": 1.725
}[activity]

# ---------- CALCULATIONS ----------

bmi = calculate_bmi(
    weight,
    height
)

water = calculate_water(
    weight
)

calories = calculate_calories(
    age,
    gender,
    weight,
    height,
    activity_level
)

col1, col2, col3 = st.columns(3)

col1.metric("BMI", bmi)
col2.metric("Water Intake", f"{water} L")
col3.metric("Calories", calories)

# ---------- FOODS ----------

st.subheader("🍛 Suggested Foods")

foods = [
    {
        "name": "Rice",
        "img": "https://images.unsplash.com/photo-1516684732162-798a0062be99"
    },
    {
        "name": "Eggs",
        "img": "https://images.unsplash.com/photo-1506084868230-bb9d95c24759"
    },
    {
        "name": "Chicken",
        "img": "https://images.unsplash.com/photo-1604503468506-a8da13d82791"
    }
]

cols = st.columns(3)

for i, food in enumerate(foods):
    with cols[i]:
        st.image(food["img"])
        st.write(food["name"])

st.subheader("🏋️ AI Workout Plan")

if st.button("Generate Workout"):

    prompt = f"""
    Age: {age}
    Weight: {weight}
    Goal: {goal}

    Create a workout plan.
    """

    workout = ask_gemini(prompt)

    st.session_state["workout"] = workout

    st.write(workout)

# ---------- MEAL ----------

st.subheader("🍽️ AI Meal Plan")

if st.button("Generate Meal Plan"):

    prompt = f"""
    Calories: {calories}
    Goal: {goal}

    Create a one-day Indian meal plan.
    """

    meal = ask_gemini(prompt)

    st.session_state["meal"] = meal

    st.write(meal)

# ---------- CHATBOT ----------

st.subheader("💬 AI Fitness Coach")

if "messages" not in st.session_state:
    st.session_state.messages = []

user_message = st.chat_input(
    "Ask a fitness question..."
)

if user_message:

    st.session_state.messages.append(
        {
            "role": "user",
            "content": user_message
        }
    )

    reply = ask_gemini(user_message)

    st.session_state.messages.append(
        {
            "role": "assistant",
            "content": reply
        }
    )

for msg in st.session_state.messages:

    with st.chat_message(msg["role"]):
        st.write(msg["content"])

# ---------- WEIGHT TRACKING ----------

st.subheader("📈 Weight Tracking")

if "weight_history" not in st.session_state:
    st.session_state.weight_history = []

if st.button("Save Current Weight"):

    st.session_state.weight_history.append(
        weight
    )

if len(st.session_state.weight_history) > 0:

    df = pd.DataFrame(
        {
            "Weight": st.session_state.weight_history
        }
    )

    st.line_chart(df)

# ---------- PDF DOWNLOAD ----------

st.subheader("📄 Download Report")

report = f"""
BMI: {bmi}

Calories: {calories}

Water Intake: {water}

Goal: {goal}

Workout:
{st.session_state.get('workout', '')}

Meal:
{st.session_state.get('meal', '')}
"""

pdf_file = create_pdf(report)

with open(pdf_file, "rb") as file:

    st.download_button(
        "Download PDF",
        file,
        file_name="fitness_report.pdf",
        mime="application/pdf"
    )



