# -*- coding: utf-8 -*-
# """fitness project.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1U5GQp6Fbv61VX35SLiUmg5fiLJ39MJYI
# """

# !pip install streamlit
# !pip install genai
# !pip install reportlab
# !pip install platypus

import os
import tempfile
from datetime import datetime

import db
import streamlit as st
import pandas as pd
from google import genai
from google.genai import types
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

api_key = os.getenv("GEMINI_API_KEY")

client = genai.Client(
    api_key=api_key
)

db.init_db()

def calculate_bmi(weight, height):
    height_m = height / 100
    return round(weight / (height_m ** 2), 2)

def calculate_water(weight):
    return round(weight * 0.033, 2)

def calculate_calories(age, gender, weight, height, activity):
    if gender == "Male":
        bmr = 10 * weight + 6.25 * height - 5 * age + 5
    else:
        bmr = 10 * weight + 6.25 * height - 5 * age - 161

    return round(bmr * activity)

def ask_gemini(prompt):
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    return response.text

def transcribe_audio(audio_bytes):
    """Send recorded audio straight to Gemini (multimodal) and get back plain text.
    Avoids extra deps like speech_recognition/pyaudio which don't play well on
    Streamlit Cloud."""
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=[
            types.Part.from_bytes(data=audio_bytes, mime_type="audio/wav"),
            "Transcribe this audio to plain text. Return ONLY the transcription, "
            "no preamble, no quotes."
        ]
    )
    return response.text.strip()

def create_pdf(content):
    temp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    doc = SimpleDocTemplate(temp.name)

    styles = getSampleStyleSheet()

    story = [
        Paragraph(content, styles["BodyText"])
    ]

    doc.build(story)

    return temp.name

# ---------- VALIDATION ----------

# WHO adult BMI bands. Anything outside plausible human ranges also gets flagged
# so garbage inputs (e.g. weight=25 for an adult) don't silently produce a plan.
MIN_PLAUSIBLE_ADULT_WEIGHT = 35  # kg, rough floor for anyone above pediatric age
SEVERE_UNDERWEIGHT_BMI = 16.0
UNDERWEIGHT_BMI = 18.5
OVERWEIGHT_BMI = 25.0
OBESE_BMI = 30.0

def validate_profile(age, weight, height, goal, bmi):
    """Returns (errors, warnings).
    errors  -> hard stop, don't generate a plan (implausible / unsafe combo)
    warnings -> show but allow user to proceed if they explicitly acknowledge
    """
    errors = []
    warnings = []

    if age < 18 and weight < 30:
        errors.append(
            "This weight/age combination is outside what this tool is built to "
            "handle safely. Please consult a pediatrician or doctor instead."
        )

    if age >= 18 and weight < MIN_PLAUSIBLE_ADULT_WEIGHT:
        errors.append(
            f"{weight} kg is not a plausible weight for an adult of age {age}. "
            "Please double-check the value you entered."
        )

    if bmi < SEVERE_UNDERWEIGHT_BMI:
        errors.append(
            f"A BMI of {bmi} falls into the severely underweight range. This app "
            "will not generate a weight-loss plan at this BMI — please speak to a "
            "doctor or dietitian first."
        )
        if goal == "Fat Loss":
            errors.append("Fat Loss is not offered as a goal at this BMI.")
    elif bmi < UNDERWEIGHT_BMI and goal == "Fat Loss":
        warnings.append(
            f"BMI is {bmi}, which is in the underweight range. Weight loss isn't "
            "recommended here — consider switching the goal to Maintenance or "
            "Muscle Gain."
        )

    if bmi >= OBESE_BMI and goal == "Muscle Gain":
        warnings.append(
            f"BMI is {bmi} (obese range). A lean bulk / Muscle Gain plan may not "
            "be the best fit right now — Fat Loss or Maintenance is usually "
            "recommended first. Talk to a doctor if unsure."
        )

    return errors, warnings

# streamlit
st.set_page_config(
    page_title="AI Fitness Coach",
    layout="wide"
)

st.title("🏋️ AI Fitness Coach")

# ---------- SIDEBAR ----------

st.sidebar.header("User Profile")

age = st.sidebar.number_input(
    "Age",
    16,
    80,
    22
)

gender = st.sidebar.selectbox(
    "Gender",
    ["Male", "Female"]
)

weight = st.sidebar.number_input(
    "Weight (kg)",
    30.0,
    200.0,
    70.0
)

height = st.sidebar.number_input(
    "Height (cm)",
    120.0,
    220.0,
    170.0
)

goal = st.sidebar.selectbox(
    "Goal",
    [
        "Fat Loss",
        "Maintenance",
        "Muscle Gain"
    ]
)

activity = st.sidebar.selectbox(
    "Activity Level",
    ["Sedentary", "Light", "Moderate", "Heavy"]
)
activity_level = {
    "Sedentary": 1.2,
    "Light": 1.375,
    "Moderate": 1.55,
    "Heavy": 1.725
}[activity]

# ---------- DATABASE USER ----------

# One "user" row per browser session — created once, reused across reruns so
# sidebar tweaks don't spawn a new row every time Streamlit reruns the script.
if "user_id" not in st.session_state:

    st.session_state.user_id = db.create_user(
        age=age,
        gender=gender,
        height=height,
        weight=weight,
        goal=goal,
        activity_level=activity
    )

user_id = st.session_state.user_id

# ---------- CALCULATIONS ----------

bmi = calculate_bmi(
    weight,
    height
)

water = calculate_water(
    weight
)

calories = calculate_calories(
    age,
    gender,
    weight,
    height,
    activity_level
)

col1, col2, col3 = st.columns(3)

col1.metric("BMI", bmi)
col2.metric("Water Intake", f"{water} L")
col3.metric("Calories", calories)

# ---------- VALIDATION CHECK ----------

errors, warnings = validate_profile(age, weight, height, goal, bmi)

for e in errors:
    st.error(f"⛔ {e}")

for w in warnings:
    st.warning(f"⚠️ {w}")

blocked = len(errors) > 0

if blocked:
    st.info("Fix the inputs above to unlock workout/meal plan generation.")

# ---------- FOODS ----------

st.subheader("🍛 Suggested Foods")

foods = [
    {
        "name": "Rice",
        "img": "https://images.unsplash.com/photo-1516684732162-798a0062be99"
    },
    {
        "name": "Healthy Pancakes",
        "img": "https://images.unsplash.com/photo-1506084868230-bb9d95c24759"
    },
    {
        "name": "Chicken",
        "img": "https://images.unsplash.com/photo-1604503468506-a8da13d82791"
    }
]

cols = st.columns(3)

for i, food in enumerate(foods):
    with cols[i]:
        st.image(food["img"])
        st.write(food["name"])

st.subheader("🏋️ AI Workout Plan")

previous_workout = db.get_latest_plan(user_id, "workout")

if previous_workout:

    with st.expander("📋 Previous Workout Plan"):

        st.write(previous_workout)

if st.button("Generate Workout", disabled=blocked):

    prompt = f"""
    You are a certified fitness trainer.

    Age: {age}
    Gender: {gender}
    Weight: {weight} kg
    Height: {height} cm
    BMI: {bmi}
    Goal: {goal}
    Activity Level: {activity}

    Create a detailed 7-day workout plan.

    Include:
    - Warm-up
    - Main exercises
    - Sets
    - Reps
    - Rest time
    - Cardio
    - Cool-down
    - Safety tips
    """

    workout = ask_gemini(prompt)

    st.session_state["workout"] = workout
    db.save_plan(user_id, "workout", workout)

    st.write(workout)

# ---------- MEAL ----------

st.subheader("🍽️ AI Meal Plan")

previous_meal = db.get_latest_plan(user_id, "meal")

if previous_meal:

    with st.expander("🍽️ Previous Meal Plan"):

        st.write(previous_meal)

if st.button("Generate Meal Plan", disabled=blocked):

    prompt = f"""
    You are a professional Indian nutritionist.

    Age: {age}
    Gender: {gender}
    Weight: {weight}
    Height: {height}
    BMI: {bmi}
    Calories Required: {calories}
    Goal: {goal}

    Generate a healthy one-day Indian meal plan.

    Include:

    Breakfast

    Morning Snack

    Lunch

    Evening Snack

    Dinner

    Approximate calories for each meal.

    Protein, carbs and fats.

    Water recommendation.
    """

    meal = ask_gemini(prompt)

    st.session_state["meal"] = meal
    db.save_plan(user_id, "meal", meal)

    st.write(meal)

# ---------- CHATBOT ----------

st.subheader("💬 AI Fitness Coach")

if "messages" not in st.session_state:

    history = db.get_chat_history(user_id)

    st.session_state.messages = []

    for role, message in history:

        st.session_state.messages.append(
            {
                "role": role,
                "content": message
            }
        )
# Voice input — records in-browser, transcribes via Gemini, then feeds the
# chat pipeline exactly like typed text would.
st.caption("🎙️ Ask by voice, or type below")
audio_value = st.audio_input("Record a question")

voice_message = None
if audio_value is not None:
    # Only transcribe once per new recording
    audio_bytes = audio_value.getvalue()
    audio_hash = hash(audio_bytes)
    if st.session_state.get("last_audio_hash") != audio_hash:
        with st.spinner("Transcribing..."):
            try:
                voice_message = transcribe_audio(audio_bytes)
                st.session_state["last_audio_hash"] = audio_hash
            except Exception as e:
                st.error(f"Couldn't transcribe audio: {e}")

if voice_message:
    st.caption(f"Heard: \"{voice_message}\"")

typed_message = st.chat_input(
    "Ask a fitness question..."
)

user_message = typed_message or voice_message

if user_message:

    st.session_state.messages.append(
        {
            "role": "user",
            "content": user_message
        }
    )
    db.log_chat(user_id, "user", user_message)

    reply = ask_gemini(user_message)

    st.session_state.messages.append(
        {
            "role": "assistant",
            "content": reply
        }
    )
    db.log_chat(user_id, "assistant", reply)

for msg in st.session_state.messages:

    with st.chat_message(msg["role"]):
        st.write(msg["content"])

# ---------- WEIGHT TRACKING ----------

st.subheader("📈 Weight Tracking")

if st.button("Save Current Weight"):
    db.log_weight(user_id, weight)
    st.success(f"Saved {weight} kg to database.")

weight_rows = db.get_weight_history(user_id)

if len(weight_rows) > 0:

    df = pd.DataFrame(weight_rows, columns=["Weight", "Logged At"])

    st.line_chart(df.set_index("Logged At")["Weight"])
    st.dataframe(df, use_container_width=True)

# ---------- PDF DOWNLOAD ----------

st.subheader("📄 Download Fitness Report")

# BMI Status
if bmi < 18.5:
    bmi_status = "Underweight"
elif bmi < 25:
    bmi_status = "Healthy"
elif bmi < 30:
    bmi_status = "Overweight"
else:
    bmi_status = "Obese"

# Chat History
chat_history = ""

for msg in st.session_state.messages:
    chat_history += f"{msg['role'].capitalize()}: {msg['content']}\n\n"

# Weight History
weight_history = ""

history = db.get_weight_history(user_id)

for w, d in history:
    weight_history += f"{d[:10]} : {w} kg\n"

report = f"""
==============================
      AI FITNESS REPORT
==============================

Report Generated:
{datetime.now().strftime("%d-%m-%Y %I:%M %p")}

---------------------------------
USER DETAILS
---------------------------------

Age           : {age}
Gender        : {gender}
Height        : {height} cm
Weight        : {weight} kg

Goal          : {goal}
Activity      : {activity}

---------------------------------
HEALTH SUMMARY
---------------------------------

BMI           : {bmi}
BMI Status    : {bmi_status}

Calories      : {calories} kcal/day

Water Intake  : {water} Litres/day

---------------------------------
AI WORKOUT PLAN
---------------------------------

{st.session_state.get("workout","Not Generated")}

---------------------------------
AI MEAL PLAN
---------------------------------

{st.session_state.get("meal","Not Generated")}

---------------------------------
WEIGHT HISTORY
---------------------------------

{weight_history}

---------------------------------
CHAT HISTORY
---------------------------------

{chat_history}

=================================
Thank you for using
AI Fitness Coach ❤️
=================================
"""

pdf_file = create_pdf(report)

with open(pdf_file, "rb") as file:

    st.download_button(
        "📥 Download Fitness Report",
        data=file,
        file_name="AI_Fitness_Report.pdf",
        mime="application/pdf"
    )
